version: '3'

services:
  api:
    build: .
    container_name: ecommerce
    image: api-ecommerce
    ports:
      - 3030:3030
    volumes:
      - ./:/home/app/api-ecommerce
    tty: true
    command: npm run dev
