version: '3'

services:
  api:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: api-ecommerce
    ports:
      - 3030:3030
    volumes:
      - ./:/home/app/api-ecommerce
    tty: true
